version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vape-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vape_cms
      POSTGRES_USER: vape_user
      POSTGRES_PASSWORD: vape_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vape-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vape-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - vape-network
    volumes:
      - ./uploads:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.podzoon.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v3.0
    container_name: vape-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=YOU@EMAIL.COM"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - vape-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.podzoon.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

volumes:
  postgres_data:


networks:
  vape-network:
    external: true
