services:
  postgres:
    image: postgres:15-alpine
    container_name: vape-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vape_cms
      POSTGRES_USER: vape_user
      POSTGRES_PASSWORD: vape_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vape-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vape-backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - vape-network
    volumes:
      - ./uploads:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.podzoon.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  traefik:
    image: traefik:v3.0
    container_name: vape-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # redirect http -> https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # ACME (Let's Encrypt) config
      - "--certificatesresolvers.myresolver.acme.email=YOU@EMAIL.COM"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--log.level=INFO"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # ใช้โฟลเดอร์ traefik ใน home ของคุณเพื่อเก็บ acme.json/ไฟล์อื่นๆ
      - /home/bookchaowalit/traefik:/letsencrypt
    networks:
      - vape-network
    labels:
      - "traefik.enable=true"
      # Dashboard ผ่าน subdomain (traefik.podzoon.com) — ปรับ DNS ให้ชี้มาที่ IP ด้วย
      - "traefik.http.routers.traefik.rule=Host(`traefik.podzoon.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # ตัวอย่าง Basic Auth middleware (ต้องสร้าง hash ก่อน แล้วใส่ค่าแทนด้านล่าง)
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=user:$$apr1$$REPLACE_WITH_HASH"

volumes:
  postgres_data:


networks:
  vape-network:
    external: true
